### ISSUE TITLE
Protected areas destroyed with TNT

### ISSUE THREAD

**Issue by luca28pet** [LDX-MCPE/iProtector#10]
Players can place and prime a tnt next to a protected area, and the explosion will break blocks in it.

**Comment by LDX-MCPE** [comment]
Right. I'll look into that for the future.

**Comment by LDX-MCPE** [comment]
Luckily, we won't have to worry about this until working Creepers get added to PocketMine.

**Comment by Exxarion** [comment]
Just use BanItem to ban TNT.

**Comment by LDX-MCPE** [comment]
Then what about servers that want players to have TNT? I'll add it soon.

**Comment by LDX-MCPE** [comment]
I now know a method to fix this.

**Comment by LDX-MCPE** [comment]
Fixing...

**Comment by LDX-MCPE** [comment]
Will no longer be counted as a bug, but a lack of feature, and will be managed via #21.
