### ISSUE TITLE
Flags

### ISSUE THREAD

**Issue by Exxarion** [LDX-MCPE/iProtector#11]
When typing in a flag (edit, god, touch), it says flag not found

**Comment by LDX-MCPE** [comment]
Are you sure that you're typing the arguments in the correct order? I fixed that bug yesterday before the 3.0 release.

**Comment by Exxarion** [comment]
Yup. Im typing /area flag (AREANAME) god

**Comment by Exxarion** [comment]
Nevermind, it is working again.
