### ISSUE TITLE
New flag ideas

### ISSUE THREAD

**Issue by Exxarion** [LDX-MCPE/iProtector#15]
Had an idea for a new flag: leave and enter

Leave: If this flag is off, players will not be able to leave the protected area

Enter: If this flag is off, players will not be able to enter the protected area

Do not use at the same time! XD

**Comment by LDX-MCPE** [comment]
Maybe the opposite...?

**Comment by Exxarion** [comment]
Ok, maybe it is off by default :stuck_out_tongue_closed_eyes:

**Comment by LDX-MCPE** [comment]
I meant maybe so the player can't enter an area. XD

**Comment by Exxarion** [comment]
Well then maybe another flag: Enter

Prevents users from entering an area

**Comment by Exxarion** [comment]
Updated the Original post displaying 2 new flag ideas.

**Comment by LDX-MCPE** [comment]
I can't really see how the leave flag would be possible. What if there were multiple areas with that flag?

**Comment by LDX-MCPE** [comment]
Please see #21.
