### ISSUE TITLE
Flag Idea

### ISSUE THREAD

**Issue by MCPEPIG** [LDX-MCPE/iProtector#18]
Can you add a anti-pvp flag that disallows you to hit people when you're in an area with that flag?

**Comment by TonyDroidd** [comment]
that plugin has a Flag that does that

/area flag <areaname> god true

**Comment by MCPEPIG** [comment]
That's notto wat I want.

**Comment by MCPEPIG** [comment]
I want it where you can't attack people that aren't in the area, so people can't attack players from safe zone in my PvP Arena.

**Comment by TonyDroidd** [comment]
The flag '/area flag god true' do that .-.

**Comment by MCPEPIG** [comment]
You still don't understand. Get out of here if you don't know what I mean.

**Comment by MCPEPIG** [comment]
The God flag turns PVP off only for the area but won't disable hitting players that are outside the area, which is wat the flag should do so people won't attack players from safe zones in my PvP arena. Don't make me repeat myself 6000 times.

**Comment by LDX-MCPE** [comment]
I understand. I'm wondering if I should just modify the god flag so that you can't get hurt by people in god areas. Opinion?

**Comment by MCPEPIG** [comment]
Probably

**Comment by LDX-MCPE** [comment]
Please check #21.
