### ISSUE TITLE
it doesnt work the iprotector

### ISSUE THREAD

**Issue by SoyPro** [LDX-MCPE/iProtector#23]
Because i put in the gane in chat /area pos1,/area pos2 and /area create name.i deop me and i break a block or place And the block break.can you help me.or fix it.thanks!

**Comment by LDX-MCPE** [comment]
Some people are experiencing this bug. I have not yet been able to reproduce it, but I will keep trying.

**Comment by SoyPro** [comment]
Thanks.a question.i have got signs in my server for example [Warp]name.the players have not permissions when they touch them.is your plugin or other plugin?.

**Comment by LDX-MCPE** [comment]
That's caused by another plugin.

**Comment by SoyPro** [comment]
Thanks nos yes.great job!keep up the good work!
