### ISSUE TITLE
iProtector 3.1bm2

### ISSUE THREAD

**Issue by FocusedSG** [LDX-MCPE/iProtector#33]
May I please know where to get 3.1bm2 version of iProtector? I've seen that version on many LEET servers and the touch flag is working. Is it a custom version?

**Comment by kabluinc** [comment]
any luck finding that version?

**Comment by LDX-MCPE** [comment]
The touch flag is working in the official version, too, if you use it right... The bm2 is a modified version by LEET, they haven't given me access to it.
