### ISSUE TITLE
Can i recreate this plugin?

### ISSUE THREAD

**Issue by jrodr10** [LDX-MCPE/iProtector#34]
This plugin doesnt work.... if it does you have to handle with extreme care. I would like permission to rewrite this plugin so its like... ya know... working. (Congrats on what youve made so far but the bugs are just too much man.... fix like asap or allow me to rewrite this)

**Comment by Bamuel** [comment]
Ofcourse you can recreate this plugin, you can either make your own or edit from exsisting one and then Pull Request it

**Comment by jrodr10** [comment]
ok

**Comment by LDX-MCPE** [comment]
iProtector has no bugs whatsoever, merely misuse by users. What you said is true, however. It does have to be handled with great care to be mastered and used with power, and I do apologize for such.
