### ISSUE TITLE
Multi-world Support

### ISSUE THREAD

**Issue by LDX-MCPE** [LDX-MCPE/iProtector#7]
- [x] Configuration file
- [x] World protection
- [x] Complete multi-world support

**Comment by MegaSamNinja** [comment]
Please hurry a little with the multiworld support.

Cause my players can't edit Free World

**Comment by LDX-MCPE** [comment]
Oh yeah...

**Comment by TonyDroidd** [comment]
:v

**Comment by LDX-MCPE** [comment]
Almost done!
